### ISSUE TITLE
Where is the source code of rpc.kraken.fm?

### ISSUE THREAD

**Issue by AlexR1712** [MixinNetwork/kraken.fm#1]
Hello! How we can see the source code of rpc.kraken.fm?

**Comment by cedricfung** [comment]
Hi, the server is a deployment of https://github.com/pion/ion and https://github.com/coturn/coturn,  I write some script to wrap the ion API as HTTP.

**Comment by AlexR1712** [comment]
@cedricfung Thanks, And do you have any demonstration of how it was implemented? I am not very clear about the pion documentation, it is not easy to start with it, since I do not see examples of the implementation that you indicated.

**Comment by cedricfung** [comment]
Please stay tuned, we will release all the server code after it is finished.

**Comment by cedricfung** [comment]
The server code is at the kraken repo now.
