### ISSUE TITLE
The restart logic is not work now

### ISSUE THREAD

**Issue by maggch97** [MixinNetwork/kraken.fm#6]
`res.error && typeof res.error === 'string' && res.error.indexOf(unameRPC + ' not found in')`

res.error from kraken is object instead of string.
`indexOf` can not be used like the above code. If the substring does not exist, indexOf will return -1 and the restart logic will be invoked.

**Comment by maggch97** [comment]
May be I can create a PR to fix this. But I still have some questions.
There are 3 error codes now. How could we deal with ErrorTrackNotFound?
Do we need to check the ICE connection state or we can only check the error code from server.

**Comment by cedricfung** [comment]
Excellent, thank you very much.
